"""Technical-only exact continuation for accepted WS-HPG v1.0 training."""

IMPLEMENTATION_STATUS = "WS_HPG_V1_EXACT_CONTINUATION_PREPARATION_ONLY"
NOT_PROVEN_STATUS = "WS_HPG_V1_EXACT_RESUME_NOT_PROVEN"
PLANNED_PAUSE_STATUS = "WS_HPG_V1_PLANNED_PAUSE_EPOCH60"
