inherits:
  - d15_m8_basic_speedfix_chunkaware_b16_w2_cache8.yaml

run_name: d15_m8_basic_speedfix_compile_default
run:
  config_name: d15_m8_basic_speedfix_compile_default

training:
  compile_model: true
  use_compile: true
  compile_mode: default
  compile_backend: inductor
  compile_fullgraph: false
