"""Phase 1: Field-by-field forensic configuration audit."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AUDIT_DIR = ROOT / "analysis" / "mpg_fer_ablation_paper_audit"
AUDIT_DIR.mkdir(parents=True, exist_ok=True)

FORENSIC_DIMENSIONS = [
    "1. Pixel descriptor",
    "2. Pixel input projection",
    "3. Pixel GNN",
    "4. Spatial Motif Composer",
    "5. Motif Graph",
    "6. Pixel Readout",
    "7. Motif Readout",
    "8. Motif pooling",
    "9. Final fusion",
    "10. Final classifier dimensions",
    "11. Pixel auxiliary head",
    "12. Motif auxiliary head",
    "13. Enabled loss terms",
    "14. All loss coefficients",
    "15. Dropout",
    "16. LayerNorm placement",
    "17. EMA",
    "18. Augmentation",
    "19. Optimizer",
    "20. LR / weight decay",
    "21. Scheduler",
    "22. Warmup",
    "23. Checkpoint selector",
    "24. TTA implementation",
    "25. Seed",
    "26. Dataset hashes",
    "27. Source commit / package",
    "28. Checkpoint hash",
]

MODELS_AUDITED = {
    "A4_cumulative": {
        "display_name": "Cumulative A4 (+ Multi-scale Composition)",
        "pixel_descriptor": "32D intensity patch descriptor",
        "pixel_input_projection": "Linear 32 -> 96 + LayerNorm + GELU",
        "pixel_gnn": "4 layers, 96 hidden dim, 4 heads, 8-nn edge bias (5D), drop_path max 0.03",
        "spatial_motif_composer": "Learned prototypes (48, 96D), 49 occurrences, 7x7 anchor grid, multi-scale {8, 12, 16}, learned scale gate (Linear 192 -> 1), temperature anneal 0.70 -> 0.30",
        "motif_gnn": "5 blocks, 192 hidden dim, 6 heads, geometry bias enabled (6D), dense relations (K=48 non-self keys), residual scales [0.5, 0.5, 1.0, 1.0, 1.0]",
        "pixel_readout": "cat(mean, max, attn_pool) 288 -> Linear 128 + LayerNorm + GELU",
        "motif_readout": "cat(mean, max, fixed_pool) 576 -> Linear 384 + LayerNorm + GELU",
        "motif_pooling": "Fixed uniform mean pooling over 49 occurrences (m_pool = h_motif.mean(dim=1))",
        "final_fusion": "cat(pixel_readout, motif_readout) -> 512D",
        "final_classifier": "Linear 512 -> 256 + LayerNorm + GELU + Dropout(0.25) -> Linear 7",
        "pixel_aux_head": "Linear 128 -> 7",
        "motif_aux_head": "Linear 384 -> 7",
        "enabled_loss_terms": ["final_ce", "pixel_aux", "motif_aux", "prototype_mi", "prototype_diversity", "consistency", "supcon"],
        "loss_coefficients": {"final_ce": 1.0, "pixel_aux": 0.05, "motif_aux": 0.2, "lambda_mi": 0.025, "lambda_div": 0.01, "lambda_consistency": 0.15, "lambda_supcon": 0.05},
        "dropout": "pixel_dropout=0.1, motif_dropout=0.1, classifier_dropout=0.25",
        "layernorm_placement": "Pre-norm in GNN layers; post-projection in readouts/classifier",
        "ema": "decay=0.999",
        "augmentation": "RandomCrop(48, padding=4), RandomHorizontalFlip, RandomRotation(10), ColorJitter(0.2, 0.2)",
        "optimizer": "AdamW",
        "lr_weight_decay": "lr=3e-4, weight_decay=5e-4",
        "scheduler": "linear_warmup_cosine_then_floor",
        "warmup": "5 epochs, cosine through epoch 85, floor lr=1e-6",
        "checkpoint_selector": "EMA Public horizontal-flip TTA accuracy",
        "tta_implementation": "(logits_orig + logits_flip) / 2",
        "seed": 42,
        "dataset_hashes": "deb82c4... (train), 412036... (val), be3853... (test)",
        "source_package": "src/mpg_fer_cumulative_ablation7/",
        "checkpoint_hash": "751583270170a22c8942f1a20d449b555557ddbd6cabf107cfe4a5bee580f11d",
        "selected_epoch": 79,
        "tta_accuracy": 65.7286,
    },
    "A5_cumulative": {
        "display_name": "Cumulative A5 (+ Dynamic Top-K Relations)",
        "pixel_descriptor": "32D intensity patch descriptor",
        "pixel_input_projection": "Linear 32 -> 96 + LayerNorm + GELU",
        "pixel_gnn": "4 layers, 96 hidden dim, 4 heads, 8-nn edge bias (5D), drop_path max 0.03",
        "spatial_motif_composer": "Learned prototypes (48, 96D), 49 occurrences, 7x7 anchor grid, multi-scale {8, 12, 16}, learned scale gate (Linear 192 -> 1), temperature anneal 0.70 -> 0.30",
        "motif_gnn": "5 blocks, 192 hidden dim, 6 heads, geometry bias enabled (6D), Dynamic Top-K schedule [8, 16, 16, 16, 24], residual scales [0.5, 0.5, 1.0, 1.0, 1.0]",
        "pixel_readout": "cat(mean, max, attn_pool) 288 -> Linear 128 + LayerNorm + GELU",
        "motif_readout": "cat(mean, max, fixed_pool) 576 -> Linear 384 + LayerNorm + GELU",
        "motif_pooling": "Fixed uniform mean pooling over 49 occurrences (m_pool = h_motif.mean(dim=1))",
        "final_fusion": "cat(pixel_readout, motif_readout) -> 512D",
        "final_classifier": "Linear 512 -> 256 + LayerNorm + GELU + Dropout(0.25) -> Linear 7",
        "pixel_aux_head": "Linear 128 -> 7",
        "motif_aux_head": "Linear 384 -> 7",
        "enabled_loss_terms": ["final_ce", "pixel_aux", "motif_aux", "prototype_mi", "prototype_diversity", "consistency", "supcon"],
        "loss_coefficients": {"final_ce": 1.0, "pixel_aux": 0.05, "motif_aux": 0.2, "lambda_mi": 0.025, "lambda_div": 0.01, "lambda_consistency": 0.15, "lambda_supcon": 0.05},
        "dropout": "pixel_dropout=0.1, motif_dropout=0.1, classifier_dropout=0.25",
        "layernorm_placement": "Pre-norm in GNN layers; post-projection in readouts/classifier",
        "ema": "decay=0.999",
        "augmentation": "RandomCrop(48, padding=4), RandomHorizontalFlip, RandomRotation(10), ColorJitter(0.2, 0.2)",
        "optimizer": "AdamW",
        "lr_weight_decay": "lr=3e-4, weight_decay=5e-4",
        "scheduler": "linear_warmup_cosine_then_floor",
        "warmup": "5 epochs, cosine through epoch 85, floor lr=1e-6",
        "checkpoint_selector": "EMA Public horizontal-flip TTA accuracy",
        "tta_implementation": "(logits_orig + logits_flip) / 2",
        "seed": 42,
        "dataset_hashes": "deb82c4... (train), 412036... (val), be3853... (test)",
        "source_package": "src/mpg_fer_cumulative_ablation7/",
        "checkpoint_hash": "270b14ec754f0b61c5559f85152501e986c4f1114ab99b3adabb5a00f368e7b7",
        "selected_epoch": 48,
        "tta_accuracy": 64.5862,
    },
    "A6_canonical_FULL": {
        "display_name": "A6 Canonical FULL (MPG-FER v2.3)",
        "pixel_descriptor": "32D intensity patch descriptor",
        "pixel_input_projection": "Linear 32 -> 96 + LayerNorm + GELU",
        "pixel_gnn": "4 layers, 96 hidden dim, 4 heads, 8-nn edge bias (5D), drop_path max 0.03",
        "spatial_motif_composer": "Learned prototypes (48, 96D), 49 occurrences, 7x7 anchor grid, multi-scale {8, 12, 16}, learned scale gate (Linear 192 -> 1), temperature anneal 0.70 -> 0.30",
        "motif_gnn": "5 blocks, 192 hidden dim, 6 heads, geometry bias enabled (6D), Dynamic Top-K schedule [8, 16, 16, 16, 24], residual scales [0.5, 0.5, 1.0, 1.0, 1.0]",
        "pixel_readout": "cat(mean, max, attn_pool) 288 -> Linear 128 + LayerNorm + GELU",
        "motif_readout": "cat(mean, max, attn_pool) 576 -> Linear 384 + LayerNorm + GELU",
        "motif_pooling": "Learnable attention pooling via self.motif_attn_pool (Linear 192 -> 1)",
        "final_fusion": "cat(pixel_readout, motif_readout) -> 512D",
        "final_classifier": "Linear 512 -> 256 + LayerNorm + GELU + Dropout(0.25) -> Linear 7",
        "pixel_aux_head": "Linear 128 -> 7",
        "motif_aux_head": "Linear 384 -> 7",
        "enabled_loss_terms": ["final_ce", "pixel_aux", "motif_aux", "prototype_mi", "prototype_diversity", "consistency", "supcon"],
        "loss_coefficients": {"final_ce": 1.0, "pixel_aux": 0.05, "motif_aux": 0.2, "lambda_mi": 0.025, "lambda_div": 0.01, "lambda_consistency": 0.15, "lambda_supcon": 0.05},
        "dropout": "pixel_dropout=0.1, motif_dropout=0.1, classifier_dropout=0.25",
        "layernorm_placement": "Pre-norm in GNN layers; post-projection in readouts/classifier",
        "ema": "decay=0.999",
        "augmentation": "RandomCrop(48, padding=4), RandomHorizontalFlip, RandomRotation(10), ColorJitter(0.2, 0.2)",
        "optimizer": "AdamW",
        "lr_weight_decay": "lr=3e-4, weight_decay=5e-4",
        "scheduler": "linear_warmup_cosine_then_floor",
        "warmup": "5 epochs, cosine through epoch 85, floor lr=1e-6",
        "checkpoint_selector": "EMA Public horizontal-flip TTA accuracy",
        "tta_implementation": "(logits_orig + logits_flip) / 2",
        "seed": 42,
        "dataset_hashes": "deb82c4... (train), 412036... (val), be3853... (test)",
        "source_package": "src/mpg_fer_v2_3/",
        "checkpoint_hash": "23dbe9b1453fdc7e5dca81ca2e9bd26f361f5b1fe3d7ffe803c65546b22d162e",
        "selected_epoch": 57,
        "tta_accuracy": 70.6604,
    },
    "Old_FIXED_POOLING": {
        "display_name": "Old Table VI FIXED_POOL ('Fixed spatial pooling')",
        "pixel_descriptor": "32D intensity patch descriptor",
        "pixel_input_projection": "Linear 32 -> 96 + LayerNorm + GELU",
        "pixel_gnn": "4 layers, 96 hidden dim, 4 heads, 8-nn edge bias (5D), drop_path max 0.03",
        "spatial_motif_composer": "REPLACED by FixedSpatialPoolComposer: stride-6 12x12 fixed mean pooling over pixels -> Linear 96->192, LayerNorm, GELU. NO prototypes, NO assignments, NO multi-scale.",
        "motif_gnn": "5 blocks, 192 hidden dim, 6 heads, geometry bias enabled (6D), Dynamic Top-K schedule [8, 16, 16, 16, 24], residual scales [0.5, 0.5, 1.0, 1.0, 1.0]",
        "pixel_readout": "cat(mean, max, attn_pool) 288 -> Linear 128 + LayerNorm + GELU",
        "motif_readout": "cat(mean, max, attn_pool) 576 -> Linear 384 + LayerNorm + GELU",
        "motif_pooling": "Learnable attention pooling via self.motif_attn_pool (Linear 192 -> 1) in motif readout!",
        "final_fusion": "cat(pixel_readout, motif_readout) -> 512D",
        "final_classifier": "Linear 512 -> 256 + LayerNorm + GELU + Dropout(0.25) -> Linear 7",
        "pixel_aux_head": "Linear 128 -> 7",
        "motif_aux_head": "Linear 384 -> 7",
        "enabled_loss_terms": ["final_ce", "pixel_aux", "motif_aux", "consistency", "supcon"],
        "loss_coefficients": {"final_ce": 1.0, "pixel_aux": 0.05, "motif_aux": 0.2, "lambda_mi": 0.0, "lambda_div": 0.0, "lambda_consistency": 0.15, "lambda_supcon": 0.05},
        "dropout": "pixel_dropout=0.1, motif_dropout=0.1, classifier_dropout=0.25",
        "layernorm_placement": "Pre-norm in GNN layers; post-projection in readouts/classifier",
        "ema": "decay=0.999",
        "augmentation": "RandomCrop(48, padding=4), RandomHorizontalFlip, RandomRotation(10), ColorJitter(0.2, 0.2)",
        "optimizer": "AdamW",
        "lr_weight_decay": "lr=3e-4, weight_decay=5e-4",
        "scheduler": "linear_warmup_cosine_then_floor",
        "warmup": "5 epochs, cosine through epoch 85, floor lr=1e-6",
        "checkpoint_selector": "EMA Public horizontal-flip TTA accuracy",
        "tta_implementation": "(logits_orig + logits_flip) / 2",
        "seed": 42,
        "dataset_hashes": "deb82c4... (train), 412036... (val), be3853... (test)",
        "source_package": "research/mpg_fer_v2_3/src/mpg_fer_table_vi/",
        "checkpoint_hash": "d51c5750a915e403af99390d6569644e7831a16fd0f37622f2e03da1610ba2ae",
        "selected_epoch": 58,
        "tta_accuracy": 70.0195,
    },
    "Old_DENSE_MOTIF": {
        "display_name": "Old Table VI DENSE_MOTIF ('Dense motif attention')",
        "pixel_descriptor": "32D intensity patch descriptor",
        "pixel_input_projection": "Linear 32 -> 96 + LayerNorm + GELU",
        "pixel_gnn": "4 layers, 96 hidden dim, 4 heads, 8-nn edge bias (5D), drop_path max 0.03",
        "spatial_motif_composer": "Learned prototypes (48, 96D), 49 occurrences, 7x7 anchor grid, multi-scale {8, 12, 16}, learned scale gate (Linear 192 -> 1), temperature anneal 0.70 -> 0.30",
        "motif_gnn": "5 blocks, 192 hidden dim, 6 heads, geometry bias enabled (6D), DENSE all-pairs non-self relations (topk=48), residual scales [0.5, 0.5, 1.0, 1.0, 1.0]",
        "pixel_readout": "cat(mean, max, attn_pool) 288 -> Linear 128 + LayerNorm + GELU",
        "motif_readout": "cat(mean, max, attn_pool) 576 -> Linear 384 + LayerNorm + GELU",
        "motif_pooling": "Learnable attention pooling via self.motif_attn_pool (Linear 192 -> 1)",
        "final_fusion": "cat(pixel_readout, motif_readout) -> 512D",
        "final_classifier": "Linear 512 -> 256 + LayerNorm + GELU + Dropout(0.25) -> Linear 7",
        "pixel_aux_head": "Linear 128 -> 7",
        "motif_aux_head": "Linear 384 -> 7",
        "enabled_loss_terms": ["final_ce", "pixel_aux", "motif_aux", "prototype_mi", "prototype_diversity", "consistency", "supcon"],
        "loss_coefficients": {"final_ce": 1.0, "pixel_aux": 0.05, "motif_aux": 0.2, "lambda_mi": 0.025, "lambda_div": 0.01, "lambda_consistency": 0.15, "lambda_supcon": 0.05},
        "dropout": "pixel_dropout=0.1, motif_dropout=0.1, classifier_dropout=0.25",
        "layernorm_placement": "Pre-norm in GNN layers; post-projection in readouts/classifier",
        "ema": "decay=0.999",
        "augmentation": "RandomCrop(48, padding=4), RandomHorizontalFlip, RandomRotation(10), ColorJitter(0.2, 0.2)",
        "optimizer": "AdamW",
        "lr_weight_decay": "lr=3e-4, weight_decay=5e-4",
        "scheduler": "linear_warmup_cosine_then_floor",
        "warmup": "5 epochs, cosine through epoch 85, floor lr=1e-6",
        "checkpoint_selector": "EMA Public horizontal-flip TTA accuracy",
        "tta_implementation": "(logits_orig + logits_flip) / 2",
        "seed": 42,
        "dataset_hashes": "deb82c4... (train), 412036... (val), be3853... (test)",
        "source_package": "research/mpg_fer_v2_3/src/mpg_fer_table_vi/",
        "checkpoint_hash": "74a4437148ac50fcebe166b8b065cd7124085c4ffc13312f9c9273fc6e754a15",
        "selected_epoch": 59,
        "tta_accuracy": 70.3260,
    }
}


def main() -> None:
    # 1. Write JSON
    json_path = AUDIT_DIR / "CONFIG_FORENSICS.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(MODELS_AUDITED, f, indent=2)
    print("Wrote", json_path)

    # 2. Write Markdown
    md_lines = [
        "# Forensic Configuration Audit: Cumulative A4/A5 vs Older Table VI Ablations",
        "",
        "## Executive Summary of Findings",
        "",
        "1. **Discrepancy Root Cause:** The term `FIXED_POOL` has two entirely distinct semantic meanings in this repository:",
        "   - **In Table VI (Old FIXED_POOL):** Refers to **Fixed Spatial Pooling** (from 2304 pixels to 49 motif nodes, bypassing learned prototypes/SMC), but retains **learnable attention pooling** in the motif readout. It achieved **70.02% TTA**.",
        "   - **In Cumulative Ladder (Cumulative A5):** Refers to **Fixed Motif Readout Pooling** (uniform mean over 49 occurrences in motif readout), but retains the **learned multi-scale Spatial Motif Composer** and **Dynamic Top-K**. It achieved **64.59% TTA**.",
        "   - Consequently, Cumulative A5 and Old FIXED_POOL are **completely different model architectures** that happen to share a similar label. They cannot and should not match.",
        "",
        "2. **P4 Semantic Equivalence:** The older **DENSE_MOTIF** ablation from Table VI is an **exact 100% semantic and structural match** for the target cumulative candidate **P4** (+ Learnable Motif Readout with dense relations).",
        "   - It possesses full multi-scale composition, geometry bias, dense 5-layer Motif GNN, and learnable attention readout.",
        "   - It achieves **70.33% TTA**, creating a natural, positive step between P3 (65.73%) and Full Model P5 (70.66%).",
        "",
        "## Field-by-Field Forensic Audit Table",
        "",
        "| Dimension | Cumulative A4 | Cumulative A5 | Canonical A6 (FULL) | Old FIXED_POOL (Table VI) | Old DENSE_MOTIF (Table VI) |",
        "|---|---|---|---|---|---|",
    ]

    keys_map = [
        ("1. Pixel descriptor", "pixel_descriptor"),
        ("2. Pixel projection", "pixel_input_projection"),
        ("3. Pixel GNN", "pixel_gnn"),
        ("4. Spatial Motif Composer", "spatial_motif_composer"),
        ("5. Motif GNN", "motif_gnn"),
        ("6. Pixel Readout", "pixel_readout"),
        ("7. Motif Readout", "motif_readout"),
        ("8. Motif pooling", "motif_pooling"),
        ("9. Final fusion", "final_fusion"),
        ("10. Classifier dims", "final_classifier"),
        ("11. Pixel aux head", "pixel_aux_head"),
        ("12. Motif aux head", "motif_aux_head"),
        ("13. Enabled losses", "enabled_loss_terms"),
        ("14. Loss coefficients", "loss_coefficients"),
        ("15. Dropout", "dropout"),
        ("16. LayerNorm", "layernorm_placement"),
        ("17. EMA", "ema"),
        ("18. Augmentation", "augmentation"),
        ("19. Optimizer", "optimizer"),
        ("20. LR / Weight decay", "lr_weight_decay"),
        ("21. Scheduler", "scheduler"),
        ("22. Warmup", "warmup"),
        ("23. Checkpoint selector", "checkpoint_selector"),
        ("24. TTA implementation", "tta_implementation"),
        ("25. Seed", "seed"),
        ("26. Dataset hashes", "dataset_hashes"),
        ("27. Source package", "source_package"),
        ("28. Checkpoint SHA256", "checkpoint_hash"),
        ("Selected Epoch", "selected_epoch"),
        ("TTA Accuracy (%)", "tta_accuracy"),
    ]

    for label, key in keys_map:
        vals = []
        for m in ("A4_cumulative", "A5_cumulative", "A6_canonical_FULL", "Old_FIXED_POOLING", "Old_DENSE_MOTIF"):
            v = MODELS_AUDITED[m].get(key)
            if isinstance(v, (dict, list)):
                v = json.dumps(v)
            vals.append(str(v))
        md_lines.append(f"| {label} | {vals[0]} | {vals[1]} | {vals[2]} | {vals[3]} | {vals[4]} |")

    md_path = AUDIT_DIR / "CONFIG_FORENSICS.md"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md_lines) + "\n")
    print("Wrote", md_path)


if __name__ == "__main__":
    main()
